### ISSUE TITLE
当索引不可被自动创建时，会抛出错误，但包内未将错误直接提示给使用者

### ISSUE THREAD

**Issue by mouyong** [betterde/logger#12]
![image](https://user-images.githubusercontent.com/10336437/69694605-53225b00-1114-11ea-8069-15dd4dbf1c65.png)

**Comment by jinrenjie** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/5665135/69728545-981faf00-115f-11ea-8b32-d87e8a002883.png">

`ignore_error` 值为 `false` 应该能正常抛出异常的！

<img width="846" alt="image" src="https://user-images.githubusercontent.com/5665135/69728580-a968bb80-115f-11ea-86fb-dac0d5b92afa.png">

**Comment by mouyong** [comment]
那，代码表达的意思看起来，这是打算告诉用户说，「你的 es 有问题，赶紧找问题去」，然后不打算告诉用户说，「你索引没建，你不让我自动帮你建立索引嘛，或者你手动建立下索引呗」？

**Comment by mouyong** [comment]
难道是我今天调试出现了问题。我明天试试

**Comment by jinrenjie** [comment]
@mouyong ES 本身就是索引不存在的话自动创建索引和mapping。所以导致写入失败，无非是认证失败，或连接异常，不上报我想可能是因为，一般都是大批量插入，如果exception中携带1000个documens 会很奇怪吧！或许这是 monolog 留下来的坑……
