### ISSUE TITLE
queue 不支持自定义队列名问题

### ISSUE THREAD

**Issue by mouyong** [betterde/logger#13]
线上的好多队列都使用了默认队列名。如果发往 es 的日志开启了队列发送。可能会因为队列过多问题出现不可预期的错误。

期望能自定义队列名

**Comment by jinrenjie** [comment]
嗯！这个可以有，你可以在 PR 里一并改了。我发布 v1.8.2

**Comment by mouyong** [comment]
这个让给你来加功能吧？我代码设计能力还不够。

**Comment by jinrenjie** [comment]
@mouyong 👌

**Comment by mouyong** [comment]
@jinrenjie 啥时候发版本 5.6.* 的 laravel 框架？

**Comment by jinrenjie** [comment]
@mouyong 等会就发

**Comment by jinrenjie** [comment]
v1.8.2 中已添加自定义队列选项
