### ISSUE TITLE
为啥选择多一层 if 判断，这样做更合适吗？

### ISSUE THREAD

**Issue by mouyong** [betterde/logger#15]
为啥此处不用反逻辑，这样不是多了一层嵌套吗?见链接

https://github.com/betterde/logger/commit/1b2327768a124508943e2ddf7b0f95dddbb12980#r36154473

**Comment by jinrenjie** [comment]
@mouyong 举个例子我看一下，我没想到更优雅的方式！

**Comment by mouyong** [comment]
```
如果有要记录的数据，那么
    判断当前是否要 queue 发送
           queue 发送
    否则
           批量发送
```




```
如果没有要记录的数据
    不执行后边逻辑

判断当前是否要 queue 发送
       queue 发送
否则
       批量发送
```

你觉得采用哪种感觉上会好点？

**Comment by jinrenjie** [comment]
@mouyong 没有就跳过是可行的，但是我不确定在中间件中的terminate方法进行returen会不会影响整个请求生命周期……所以保守一点，if else 嵌套！

**Comment by mouyong** [comment]
@jinrenjie 那应该先看看源码呀。这样就放弃了吗。在里面 throw 会影响后面。否则一般都是不会影响循环的执行

**Comment by mouyong** [comment]
大部分情况，这种不报错都不会影响其他中间件的执行

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Http/Kernel.php#L201-L221

**Comment by jinrenjie** [comment]
@mouyong 看了一下，return 不影响逻辑，已经改了，release 了新版本！
