### ISSUE TITLE
多日志渠道下，只能产生单日志文件。

### ISSUE THREAD

**Issue by xiwang6428** [betterde/logger#16]
当我在config/logging.php配置下，想配置stack的多渠道：
'stack' => [
            'driver' => 'stack',
            'channels' => ['daily', 'elastic'],
            'ignore_exceptions' => false,
        ],
发现storage/logs下，只产生laravel.logs单日志文件，不能产生每日的日志文件。.env文件中已确认是：LOG_CHANNEL=stack配置了。

**Comment by jinrenjie** [comment]
@xiwang6428 v1.8.7 中已经修复了，但是如果使用 `stack` channel 的话，将无法使用批量发送和队列功能，因为 `stack` channel 默认使用 `Monolog\Logger` ，并不是 betterde/logger 包的 `Betterde\Logger\Logger` 。
保险做法建议只写入文件，然后通过Logstash 或者 Filebate 进行收集。
