### ISSUE TITLE
配置type判断错误

### ISSUE THREAD

**Issue by ennnnny** [betterde/logger#17]
```php
protected function getDefaultFormatter(): FormatterInterface
{
    return new ElasticsearchFormatter($this->options['index'], Arr::get($this->options['type'], 'type', ''));
}
```
`src/Handler/ElasticsearchHandler.php`文件*104*行，这里写法有问题。
`$this->options['type']`取出已经是字符串了，用`Arr::get`的话，怎样都是取不到的，也就走默认成空。后续影响`_type`的判断，导致不兼容ES旧版本。
可以将`$this->options['type']`改成`$this->options`，就一点东西，不PR了:smiley:

**Comment by jinrenjie** [comment]
@ennnnny 感谢反馈，我会尽快修复👨🏻‍💻
