### ISSUE TITLE
出现请求失败的时候，不抛出错误吗？

### ISSUE THREAD

**Issue by mouyong** [betterde/logger#4]
![image](https://user-images.githubusercontent.com/10336437/69687923-827a9d00-10ff-11ea-9155-e3f1a10674ab.png)

**Comment by jinrenjie** [comment]
忘记删除了，1.8.1 版本中会删掉

**Comment by mouyong** [comment]
@jinrenjie 可以考虑通过 pr 的 closed #xxx 来关闭
