### ISSUE TITLE
无法正确添加日志。

### ISSUE THREAD

**Issue by mouyong** [betterde/logger#8]
![image](https://user-images.githubusercontent.com/10336437/69690333-5c0c3000-1106-11ea-8fb2-d1348a2f385c.png)

![image](https://user-images.githubusercontent.com/10336437/69690287-3e3ecb00-1106-11ea-9b6f-9215b12f22bb.png)

**Comment by jinrenjie** [comment]
你的 elasticsearch 什么版本？

**Comment by jinrenjie** [comment]
我的 ES 7.4.2 没有任何问题

**Comment by mouyong** [comment]
> 你的 elasticsearch 什么版本？

7.4.0

**Comment by mouyong** [comment]
报错提示似乎是因为 7.* 的移除了 _type 信息。代码中附加了。而观望的 php client 文档也移除了。我在代码中注释后就可以成功添加。

#10 问题中提到了文档链接
