### ISSUE TITLE
关于 elasticsearch 日志索引问题

### ISSUE THREAD

**Issue by mouyong** [betterde/logger#9]
请问这个 index 是否是需要自己手动请求 elasticsearch 进行创建？还是有默认的格式？

**Comment by jinrenjie** [comment]
index 如果不存在会自动创建，但是 Kibana 查询的话还需要 进入Kibana 的 Management > Index patterns 中创建一个对应的 Index patterns

**Comment by mouyong** [comment]
@jinrenjie 好的，谢谢

**Comment by mouyong** [comment]
@jinrenjie 那想问下。有时候我们自己创建索引，指定 mapping ，是为了查询优化、索引内容吗？

**Comment by jinrenjie** [comment]
@mouyong 虽然 ES 能自动创建索引，但是对于有高度自定义的字段有查询需求的话，需要指定，这方面我也还在研究，如果有不对的地方还请指正！

**Comment by jinrenjie** [comment]
@mouyong 另外在mapping 中还可以设置一些特殊字段用特殊插件处理，比如在早先的版本中需要对中文进行分词，需要安装第三方插件，然后在mapping 中对需要分词的字段进行设置！
